language: node_js
node_js:
  - '7'
before_install:
  - npm install gulp-cli -g
install:
  - npm install
script:
  - npm test & npm run build
  branches:
    only:
    - develop
cache:
  directories:
    - node_modules